version: 2.1
orbs:
  node: circleci/node@4.2.0
  aws-cli: circleci/aws-cli@2.0.0
  eb: circleci/aws-elastic-beanstalk@1.0.0
jobs:
  # aws-cli-example:
  #   executor: aws-cli/default
  #   steps:
  #     - checkout
  #     - aws-cli/install
  #     - aws-cli/setup:
  #         profile-name: default
  #     - run: echo "Run your code here"
  # frontend:
  #   working_directory: ~/app/udagram-frontend
  #   executor: node/default
  #   steps:
  #     - checkout:
  #         path: ~/app
  #     - node/install-packages:
  #         app-dir: ~/app/udagram-frontend
  #     - run:
  #         name: Build Frontend
  #         command: npm run build
  #     - aws-cli/setup:
  #         profile-name: default 
  #         configure-default-region: true 
  #         configure-profile-region: true 
  #         disable-aws-pager: true 
  #         override-installed: false 
  #         aws-access-key-id: AWS_ACCESS_KEY 
  #         aws-secret-access-key: AWS_SECRET_ACCESS_KEY 
  #     - run:
  #         name: Deploy Frontend
  #         command: aws s3 cp --recursive --acl public-read --cache-control="max-age=0, no-cache, no-store, must-revalidate" www/ s3://udagram-meska/
  server:
    working_directory: ~/app/udagram-api
    executor: node/default
    steps:
      - checkout:
          path: ~/app
      - node/install-packages:
          app-dir: ~/app/udagram-api
      - run:
          name: Build and Archive Server
          command: |-
            npm run build
      - aws-cli/setup:
          profile-name: default 
          configure-default-region: true 
          configure-profile-region: true 
          disable-aws-pager: true 
          override-installed: false 
          aws-access-key-id: AWS_ACCESS_KEY 
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY 
      #- eb/setup
      - run:
          name: Deploy Server
          # command: |-
            # aws elasticbeanstalk create-application-version --application-name $EB_APP --version-label <<pipeline.git.revision>> --source-bundle S3Bucket="$EB_BUCKET",S3Key="Archive.zip"
            # aws elasticbeanstalk update-environment --application-name $EB_APP --environment-name $EB_ENV --version-label <<pipeline.git.revision>>
          command: |
             aws elasticbeanstalk update-environment --application-name udagram-api --environment-name Udagramapi-env
          
workflows:
  build_and_deploy:
    jobs:
      # - aws-cli-example:
      #   contex: aws
      #- frontend
      - server     